// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    interface IControlAppearance requires Microsoft.Terminal.Core.ICoreAppearance
    {
        Microsoft.Terminal.Core.Color SelectionBackground { get; };
        String BackgroundImage  { get; };
        Double BackgroundImageOpacity  { get; };
        Microsoft.UI.Xaml.Media.Stretch BackgroundImageStretchMode  { get; };
        Microsoft.UI.Xaml.HorizontalAlignment BackgroundImageHorizontalAlignment  { get; };
        Microsoft.UI.Xaml.VerticalAlignment BackgroundImageVerticalAlignment  { get; };
        // IntenseIsBold and IntenseIsBright are in Core Appearance
        Double Opacity { get; };

        // Experimental settings
        Boolean RetroTerminalEffect { get; };
        String PixelShaderPath { get; };
    };
}
