// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "TermControl.idl";

namespace Microsoft.Terminal.Control
{
    [default_interface] runtimeclass TermControlAutomationPeer :
        Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer,
        Microsoft.UI.Xaml.Automation.Provider.ITextProvider
    {

        void UpdateControlBounds();
        void SetControlPadding(Microsoft.Terminal.Core.Padding padding);
    }
}
